# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/df0c3aaa-ad10-463a-866f-41f91263ebd8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ac3184b1-8da6-4110-a6e7-e015a91dee31".device = "/dev/disk/by-uuid/ac3184b1-8da6-4110-a6e7-e015a91dee31";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/788C-6DFD";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/271f68dd-e5db-4935-a037-c6ac9be03da8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-1df67eee-4d68-47c3-bd32-a160c68752f6".device = "/dev/disk/by-uuid/1df67eee-4d68-47c3-bd32-a160c68752f6";

  fileSystems."/vault" = {
    device = "/dev/disk/by-uuid/85ef5bf5-e468-4727-912d-440e09c7b2fa";
    fsType = "ext4";
    options = ["defaults" "nofail" "users" "rw" "exec"];
  };

  boot.initrd.luks.devices."luks-192aa104-aa43-4da2-9423-c08704d987aa".device = "/dev/disk/by-uuid/192aa104-aa43-4da2-9423-c08704d987aa";

  swapDevices = [
    {device = "/dev/disk/by-uuid/d6b52230-16de-41ff-b1ba-d314d55b3474";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
